### ISSUE TITLE
Default Google category- dont support multistore

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/GoogleShopping-plugin-for-nopcommerce#1]
if i have multi store, Foods and Cars
but i can select only one Default Google category.
Needs ability to select Default Google category for each store

**Comment by DmitriyKulagin** [comment]
Done. [#commit](https://github.com/nopSolutions/GoogleShopping-plugin-for-nopcommerce/commit/4da4e7794209ecbd1d8a68a69a85281bd21d2df1)
