### ISSUE TITLE
SKUs would be better for the feed

### ISSUE THREAD

**Issue by chrisorlandodev** [nopSolutions/GoogleShopping-plugin-for-nopcommerce#13]
https://github.com/nopSolutions/GoogleShopping-plugin-for-nopcommerce/blob/0c29f484ff9666de406ecf6521be6a04ed5f6575/Nop.Plugin.Feed.GoogleShopping/GoogleShoppingService.cs#L286

As per Google

> **Best practices**
> These best practices can help you go beyond the basic requirements to optimize your product data for performance.
> 
> Use SKUs as IDs where possible. SKUs help us to understand the structure of your landing page. Since SKUs are unique, they can also help prevent you from accidentally reusing IDs.

https://support.google.com/merchants/answer/6324405?hl=en

**Comment by DmitriyKulagin** [comment]
Done, please check [this commit](https://github.com/nopSolutions/GoogleShopping-plugin-for-nopcommerce/commit/875b03a52c38961e342292d36d36fcdd4435582c).

**Comment by chrisorlandodev** [comment]
@DmitriyKulagin, thanks! 

This is great except for one thing, an upgrade of this plugin will affect people's feeds greatly as this would automatically switch IDs to SKUs. Google Merchant Center will think that they are new products. This will trickle down it Google Ads Campaigns, where we would lose the history and performance data of the ads running because Google Ads also thinks they are new products.

Perhaps this should be configurable.

I'm sorry for not including this info in the original post.
