### ISSUE TITLE
Link not generated in 4.6

### ISSUE THREAD

**Issue by gkennedy1** [nopSolutions/GoogleShopping-plugin-for-nopcommerce#17]
The product link generation is returning null since 4.6. This stops the shopping feed from working.

[The line](https://github.com/nopSolutions/GoogleShopping-plugin-for-nopcommerce/blob/875b03a52c38961e342292d36d36fcdd4435582c/Nop.Plugin.Feed.GoogleShopping/GoogleShoppingService.cs#L344)

`var productUrl = GetUrlHelper().RouteUrl("Product", new { SeName = await _urlRecordService.GetSeNameAsync(product) }, await GetHttpProtocolAsync());`

should read

`var productUrl = GetUrlHelper().RouteUrl<Product>(new { SeName = await _urlRecordService.GetSeNameAsync(product) }, await GetHttpProtocolAsync());`

**Comment by fabiorme** [comment]
Hi, is there a solution to this problem? because google merchant does not accept products without the link

**Comment by fabiorme** [comment]
hello, I solved the problem by replacing

//link [link] - URL directly linking to your item's page on your website
var productUrl = GetUrlHelper().RouteUrl("Product", new { SeName = await _urlRecordService.GetSeNameAsync(product) }, await GetHttpProtocolAsync());
writer.WriteElementString("link", productUrl);


with this code
//new link line
var SeName = await _urlRecordService.GetSeNameAsync(product);
var storeLocation1 = _webHelper.GetStoreLocation();
var product_link = storeLocation1 + SeName;
writer.WriteElementString("link", product_link);

**Comment by MuzafferSZGN** [comment]
Can you send me the working plugin?  m.sezgin933@gmail.com

**Comment by DmitriyKulagin** [comment]
See solution here #20
