### ISSUE TITLE
Product ID in product feed?

### ISSUE THREAD

**Issue by compito** [nopSolutions/GoogleShopping-plugin-for-nopcommerce#18]
Hi, I can't see that any of product ID's is included in the product feed. I have for example a product that definitely has manufacturer ID in database, but in xml there's nothing resembling the ID at all. It looks like this: 

<item>
      <g:id/>
      <title><![CDATA[Dyna till Lilla Åland stol]]></title>
      <description><![CDATA[&lt;p&gt;Tv&#228;tt: Dyna i tyg Blues kan vattentv&#228;ttas i 60 grader. Dyna i tyg Linne endast kemtv&#228;tt.&lt;/p&gt;]]></description>
      <g:google_product_category><![CDATA[Furniture]]></g:google_product_category>
      <g:product_type><![CDATA[Stolar > Lilla Åland stolar]]></g:product_type>
      <link/>
      <g:image_link>https://walfrid.se/images/thumbs/000/0006257_dyna-till-lilla-aland-stol_360.jpeg</g:image_link>
      <g:additional_image_link>https://walfrid.se/images/thumbs/000/0006258_dyna-till-lilla-aland-stol_360.jpeg</g:additional_image_link>
      <g:additional_image_link>https://walfrid.se/images/thumbs/002/0020575_dyna-till-lilla-aland-stol_360.jpeg</g:additional_image_link>
      <g:condition>new</g:condition>
      <g:expiration_date>2023-06-17</g:expiration_date>
      <g:availability>in stock</g:availability>
      <g:price>1125.00 SEK</g:price>
      <g:brand><![CDATA[Stolab]]></g:brand>
    </item>

Even in the plugin description it say that we should have an ID or two on every product, but they are not being sent to Google?

/Damir

**Comment by compito** [comment]
I guess the code got crumbled... Should be better like this: 

`<item>
      <g:id/>
      <title><![CDATA[Dyna till Lilla Åland stol]]></title>
      <description><![CDATA[&lt;p&gt;Tv&#228;tt: Dyna i tyg Blues kan vattentv&#228;ttas i 60 grader. Dyna i tyg Linne endast kemtv&#228;tt.&lt;/p&gt;]]></description>
      <g:google_product_category><![CDATA[Furniture]]></g:google_product_category>
      <g:product_type><![CDATA[Stolar > Lilla Åland stolar]]></g:product_type>
      <link/>
      <g:image_link>https://walfrid.se/images/thumbs/000/0006257_dyna-till-lilla-aland-stol_360.jpeg</g:image_link>
      <g:additional_image_link>https://walfrid.se/images/thumbs/000/0006258_dyna-till-lilla-aland-stol_360.jpeg</g:additional_image_link>
      <g:additional_image_link>https://walfrid.se/images/thumbs/002/0020575_dyna-till-lilla-aland-stol_360.jpeg</g:additional_image_link>
      <g:condition>new</g:condition>
      <g:expiration_date>2023-06-17</g:expiration_date>
      <g:availability>in stock</g:availability>
      <g:price>1125.00 SEK</g:price>
      <g:brand><![CDATA[Stolab]]></g:brand>
    </item>`

**Comment by DmitriyKulagin** [comment]
The SKU field acts as the product identifier. No other fields will be used in this implementation. So, just fill in the SKU field for your products to get them into the feed.

If you were referring to the 'brand' tag, then I don't see any issues with filling it in at the moment and in my test environment it is correctly filled in by the manufacturer's 'Name' field.

**Comment by compito** [comment]
Ok, nice to have an answer anyway. 
So SKU, if filled in will be exported. Brand is OK, it's already being exported. 

Thanks,
Damir
