### ISSUE TITLE
The link section of my products is empty

### ISSUE THREAD

**Issue by MuzafferSZGN** [nopSolutions/GoogleShopping-plugin-for-nopcommerce#20]
hello i installed the plugin and created a feed
The link section of my products is empty

https://www.kirmiziteknoloji.com/files/exportimport/1-googleshopping_4199301157.xml

**Comment by MuzafferSZGN** [comment]
how can i install the corrected plugin

**Comment by DmitriyKulagin** [comment]
You can download the updated plugin on our marketplace - https://www.nopcommerce.com/en/google-shopping-formerly-google-product-search
