### ISSUE TITLE
Name for plugin in Plugin.json still lists as Froogle

### ISSUE THREAD

**Issue by w-tbury** [nopSolutions/GoogleShopping-plugin-for-nopcommerce#3]
Just a minor naming convention issue that I wanted to point out just in case you wanted to keep everything consistent.

**Comment by DmitriyKulagin** [comment]
Done. [#commit](https://github.com/nopSolutions/GoogleShopping-plugin-for-nopcommerce/commit/4da4e7794209ecbd1d8a68a69a85281bd21d2df1)
